### ISSUE TITLE
🛑 Maple - Admin Portal is down due to sheer incompetence.

### ISSUE THREAD

**Issue by Yuno-Senpai** [zyradyl-moe/status.zyradyl.moe#23]
In [`498f300`](https://github.com/zyradyl-moe/status.zyradyl.moe/commit/498f30003b6e5660326b4a34832d8b3343040e8d
), Maple - Admin Portal (https://admin.zyradyl.moe) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by zyradyl** [comment]
The portal was purged accidentally through a combination of me refusing to leave well enough alone and iX-Systems making a hilariously unintuitive UI decision. It will be back tomorrow, most likely.

**Comment by zyradyl** [comment]
This has been rectified via the creation of a new unified portal
