### ISSUE TITLE
🛑 [Identified] Storj Node Service is down

### ISSUE THREAD

**Issue by Yuno-Senpai** [zyradyl-moe/status.zyradyl.moe#59]
In [`b0c65f1`](https://github.com/zyradyl-moe/status.zyradyl.moe/commit/b0c65f1acef9d42406dd968897b90c42db2e1847
), Storj Node Service (maple.zyradyl.moe) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by zyradyl** [comment]
Unsure what could have changed, but seeing QUIC identifying as misconfigured. May attempt a node restart.

**Comment by zyradyl** [comment]
Problem identified. Placing cloudflare in front of the domain seems to have caused issues. Investigating next steps.

**Comment by zyradyl** [comment]
Solution implemented and confirmed functional on Storj's side, now updating status check. Issue should autoclose once complete.
